name: Build, Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: .NET Artifact
        path: Source/API/bin/Debug/net5.0
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CI_CD_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        push: true
        tags: ${{ github.repository_owner }}/recipe-book:latest